brew "bash"
brew "cmake"
brew "coreutils"
brew "curl"
brew "editorconfig"
brew "fd"
brew "fnm"
brew "fzf"
brew "gettext"
brew "git", args: ["overwrite"]
brew "gopls"
brew "ripgrep"
brew "ruff"
brew "rust-analyzer"
brew "sd"
brew "shellcheck"
brew "taplo"
brew "tmux"
brew "uv"
brew "zoxide"

if OS.mac?
  cask "font-sauce-code-pro-nerd-font"
end
