brew "bash"
brew "cmake"
brew "coreutils"
brew "curl"
brew "editorconfig"
brew "fd"
brew "fnm"
brew "fzf"
brew "git", args: ["overwrite"]
brew "mise"
brew "mr"
brew "pcre"
brew "ripgrep"
brew "sd"
brew "shellcheck"
brew "taplo"
brew "tmux"
brew "uv"
brew "zoxide"

if OS.mac?
  tap "homebrew/cask-fonts"
  cask "font-sauce-code-pro-nerd-font"
end
