#!/bin/zsh -e

os=$(uname -s)
basedir=$(cd "$(dirname "${0}")"/.. && pwd -P)

export FSOUZA_DOTFILES_DIR=${FSOUZA_DOTFILES_DIR:-${basedir}}

local link_skip=( "${FSOUZA_BOOTSTRAP_LINK_SKIP[@]}" )

function __link {
	local name=${1}
	local source=${2}
	local target=${3}

	if ! (($link_skip[(Ie)$name])); then
		ln -sf "${source}" "${target}"
	fi
}

home_files=(.zshrc .editorconfig)
for file in "${home_files[@]}"; do
	__link "${file}" "${basedir}"/"${file}" "${HOME}"/"${file}"
done

mkdir -p "${HOME}"/.config
xdg_files=(tmux.conf alacritty.yml rgrc)
for file in "${xdg_files[@]}"; do
	__link "${file}" "${basedir}"/"${file}" "${HOME}"/.config/"${file}"
done

xdg_dirs=(git fd utop tmux)
for dir in "${xdg_dirs[@]}"; do
	link="${HOME}"/.config/"${dir}"
	if ! [ -L "${link}" ] && [ -d "${link}" ]; then
		echo >&2 "${link} exists, aborting"
		exit 2
	fi

	if ! [ -L "${link}" ]; then
		__link "${dir}" "${basedir}"/"${dir}" "${link}"
	fi
done

export basedir
if [ -f "${basedir}"/bootstrap/"${os}"-setup ]; then
	"${basedir}"/bootstrap/"${os}"-setup
fi

touch "${HOME}"/.zsh_sessions_disable

if command -v brew &>/dev/null; then
	brew update
	brew bundle --no-lock --no-upgrade --file "${basedir}"/bootstrap/Brewfile
fi

if command -v nvim &>/dev/null; then
	env NVIM_DEBUG=1 make -C "${basedir}"
fi
