#!/usr/bin/env python3
import os
import shutil
import subprocess
import sys
from pathlib import Path

BASEDIR = Path(__file__).parent.parent.absolute()
SYMLINK_SKIP = set(os.getenv("FSOUZA_BOOTSTRAP_LINK_SKIP", "").split())


def create_symlink(name: str, source: Path, target: Path) -> None:
    if name not in SYMLINK_SKIP:
        if target.exists() and not target.is_symlink():
            target.unlink()

        if not target.is_symlink():
            target.symlink_to(source)


def main() -> int:
    home = Path.home()
    config_dir = home / ".config"
    config_dir.mkdir(exist_ok=True)

    home_files = [".zshrc", ".editorconfig"]
    for file in home_files:
        create_symlink(file, BASEDIR / file, home / file)

    xdg_items = ["alacritty.yml", "rgrc", "git", "fd", "utop", "tmux"]
    for file in xdg_items:
        create_symlink(file, BASEDIR / file, config_dir / file)

    os_setup_script = BASEDIR / "bootstrap" / f"{sys.platform}-setup"
    if os_setup_script.exists():
        subprocess.check_call([os_setup_script])

    (home / ".zsh_sessions_disable").touch(exist_ok=True)

    if brew := shutil.which("brew"):
        subprocess.check_call([brew, "update"])
        subprocess.check_call(
            [
                brew,
                "bundle",
                "--no-lock",
                "--no-upgrade",
                "--file",
                BASEDIR / "bootstrap" / "Brewfile",
            ],
        )

    if shutil.which("nvim"):
        subprocess.check_call(
            ["make", "-C", BASEDIR],
            env={
                **os.environ,
                "NVIM_DEBUG": "1",
                "FSOUZA_DOTFILES_DIR": os.getenv("FSOUZA_DOTFILES_DIR", str(BASEDIR)),
            },
        )

    return 0


if __name__ == "__main__":
    sys.exit(main())
