pull_request_rules:
  - name: automerge
    conditions:
      - -merged
      - status-success=bootstrap (ubuntu)
      - status-success=bootstrap (macos)
      - label=automerge
    actions:
      merge:
        method: squash

  - name: delete head branch after merge
    conditions: []
    actions:
      delete_head_branch: {}

