name: New Text Object
description: Suggest a new text object
title: "New Textobj: "
labels: ["new textobj"]
body:
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label:
            The text object would be useful to more users than just me. ([You can use the API to
            create custom text objects](../#advanced-usage--api).)
          required: true
        - label: There is no lua plugin already implementing the text object in an adequate manner.
          required: true
        - label: I read the docs and checked that there is no such text object already.
          required: true
  - type: textarea
    id: textobj-requested
    attributes:
      label: Text object requested
      description: Describe what the text object is supposed to do.
    validations: { required: true }
  - type: textarea
    id: sample-text
    attributes:
      label: Sample text
      description:
        Provide sample text for the text object, including as many variations as necessary. If
        relevant, also provide examples of what should *not* be matched.
    validations: { required: true }
  - type: textarea
    id: inner-outer
    attributes:
      label: Inner/outer difference
      description:
        If the text object would differentiate between inner and outer, describe the difference.
  - type: input
    id: existing-plugin
    attributes:
      label: Vimscript plugin already implementing the text object
      description:
        If there is a plugin that already implements the text object, please link to it here.
  - type: input
    id: filetypes
    attributes:
      label: Filetypes
      description:
        Filetypes the text object is usually going to be used in. Fill in "all" if the text object is
        agnostic to the filetype.
    validations: { required: true }
