name: Build
on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master
jobs:
  bootstrap:
    strategy:
      matrix:
        os:
          - ubuntu
          - macos

    name: bootstrap
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: install bash on mac
        run: brew install bash
        if: matrix.os == 'macos'

      - name: install neovim on mac
        run: brew install neovim
        if: matrix.os == 'macos'

      - name: install neovim on linux
        run: sudo apt-get update && sudo apt-get install -y neovim
        if: matrix.os == 'ubuntu'

      - name: install shellcheck on mac
        run: brew install shellcheck
        if: matrix.os == 'macos'

      - name: install shellcheck on linux
        run: sudo apt-get update && sudo apt-get install -y shellcheck
        if: matrix.os == 'ubuntu'

      - uses: actions/checkout@master

      - run: make shellcheck

      - uses: actions/setup-node@master
        with:
          node-version: "12.x"

      - uses: avsm/setup-ocaml@master
        with:
          ocaml-version: "4.09.1"

      - uses: actions/setup-python@master
        with:
          python-version: "3.x"

      - uses: actions/setup-ruby@master
        with:
          ruby-version: "2.x"

      - uses: actions-rs/toolchain@master
        with:
          toolchain: stable

      - name: copy files to config dir
        run: |
          mkdir -p $HOME/.config
          cp -rv $PWD $HOME/.config/nvim

      - name: bootstrap from config dir
        run: |
          eval "$(opam env)"
          make -f $HOME/.config/nvim/Makefile bootstrap
