name: Build
on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master
jobs:
  bootstrap:
    strategy:
      matrix:
        os:
          - ubuntu
          - macos

    name: bootstrap
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: install bash on mac
        run: brew install bash
        if: matrix.os == 'macos'

      - uses: actions/checkout@master

      - uses: actions/setup-node@master
        with:
          node-version: '12.x'

      - uses: avsm/setup-ocaml@master
        with:
          ocaml-version: '4.08.1'

      - uses: actions/setup-python@master
        with:
          python-version: '3.x'

      - uses: actions/setup-ruby@master
        with:
          ruby-version: '2.x'

      - name: bootstrap
        run: |
          eval "$(opam env)"
          make bootstrap
