name: Build
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
jobs:
  bootstrap:
    strategy:
      matrix:
        os:
          - ubuntu
          - macos

    name: bootstrap
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: install bash on mac
        run: brew install bash
        if: matrix.os == 'macos'

      - name: install neovim nightly
        run: |
          if [ "${{ matrix.os }}" = "ubuntu" ]; then
            suffix=linux64
          else
            suffix=${{ matrix.os }}
          fi
          curl -L https://github.com/neovim/neovim/releases/download/nightly/nvim-${suffix}.tar.gz | sudo tar -C /usr/local --strip 1 -xzf -

      - name: install shellcheck on mac
        run: brew install shellcheck
        if: matrix.os == 'macos'

      - name: install shellcheck on linux
        run: sudo apt-get update && sudo apt-get install -y shellcheck
        if: matrix.os == 'ubuntu'

      - uses: actions/checkout@v2.3.0

      - run: make shellcheck

      - uses: actions/setup-node@v2.0.0
        with:
          node-version: "12.x"

      - uses: actions/setup-dotnet@v1.5.0
        with:
          dotnet-version: "3.1.x"

      - uses: avsm/setup-ocaml@v1.0.1
        with:
          ocaml-version: "4.10.0"

      - uses: actions/setup-python@v2.0.1
        with:
          python-version: "3.x"

      - uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable

      - name: copy files to config dir
        run: |
          mkdir -p $HOME/.config
          cp -rv $PWD $HOME/.config/nvim

      - name: bootstrap from config dir
        run: |
          eval "$(opam env)"
          make -f $HOME/.config/nvim/Makefile bootstrap
