name: Build
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
jobs:
  bootstrap:
    name: bootstrap
    runs-on: macos-11
    steps:
      - name: install neovim
        run: |
          curl -L https://github.com/fsouza/neovim/releases/download/nightly/nvim-macos.tar.gz | sudo tar -C /usr/local --strip 1 -xzf -

      - uses: actions/checkout@v3.0.2

      - uses: actions/setup-python@v4.1.0
        with:
          python-version: "3.10"

      - uses: actions/setup-go@v3.2.1
        with:
          go-version: "1.x"

      - uses: actions-rs/toolchain@v1.0.7
        with:
          toolchain: stable
          default: true
          components: clippy, rustfmt, rust-src

      - name: langservers cache
        id: nvim-langservers-cache
        uses: actions/cache@v3.0.4
        with:
          path: ~/.cache/nvim/langservers
          key: "${{ runner.os }}-${{ hashFiles('nvim/scripts/bootstrap.py') }}-20220128101400"

      - name: get luajit version
        id: get-luajit-version
        run: |
          echo "::set-output name=version::$(nvim --version | grep LuaJIT)"

      - name: set MACOSX_DEPLOYMENT_TARGET
        id: macosx-deployment-target
        run: |
          echo "MACOSX_DEPLOYMENT_TARGET=$(sw_vers -productVersion)" >>${GITHUB_ENV}
          echo "::set-output name=product-version::$(sw_vers -productVersion)"

      - name: hererocks cache
        id: nvim-hererocks-cache
        uses: actions/cache@v3.0.4
        with:
          path: ~/.cache/nvim/hr
          key: "${{ runner.os }}-${{ steps.get-luajit-version.outputs.version }}-${{ steps.macosx-deployment-target.outputs.product-version }}-${{ hashFiles('nvim/vimfiles-dev-1.rockspec') }}-20220128101400"

      - name: get python version
        id: get-python-version
        run: |
          echo "::set-output name=version::$(python3 --version)"

      - name: virtualenv cache
        id: nvim-virtualenv-cache
        uses: actions/cache@v3.0.4
        with:
          path: ~/.cache/nvim/venv
          key: "${{ runner.os }}-${{ hashFiles('nvim/langservers/requirements.txt') }}-${{ steps.get-python-version.outputs.version }}-20220128123800"

      - name: run setup
        run: |
          ./bootstrap/setup

      - name: nvim lint & tests
        run: |
          env FSOUZA_DOTFILES_DIR=${PWD} make nvim-tests nvim-lint
        env:
          NVIM_SKIP_TREESITTER: true
          NVIM_TEST_TIMEOUT: 10000

  pre-commit:
    name: pre-commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2

      - uses: actions/setup-python@v4.1.0
        with:
          python-version: 3.x
          cache: pip

      - name: install pre-commit
        run: pip install pre-commit

      - name: pre-commit cache
        uses: actions/cache@v3.0.4
        with:
          path: ~/.cache/pre-commit
          key: "${{ hashFiles('.pre-commit-config.yaml') }}"

      - run: pre-commit run --all-files --show-diff-on-failure
