name: Build
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
jobs:
  bootstrap:
    strategy:
      matrix:
        os:
          - ubuntu-20.04
          - macos-latest
        ocaml-version:
          - 4.11.1

    name: bootstrap
    runs-on: ${{ matrix.os }}
    steps:
      - name: install neovim nightly
        run: |
          if [ "${{ matrix.os }}" = "ubuntu-20.04" ]; then
            suffix=linux64
          else
            suffix=macos
          fi
          curl -L https://github.com/neovim/neovim/releases/download/nightly/nvim-${suffix}.tar.gz | sudo tar -C /usr/local --strip 1 -xzf -

      - name: install deps on mac
        if: matrix.os == 'macos-latest'
        run: |
          brew install bash shellcheck ninja libyaml luarocks elixir
          luarocks install luacheck

      - name: install deps on ubuntu
        if: matrix.os == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck ninja-build libyaml-dev luarocks
          sudo luarocks install luacheck

      - uses: actions/checkout@v2.3.3

      - run: make shellcheck

      - run: make luacheck

      - uses: actions/setup-node@v2.1.2
        with:
          node-version: "14.x"

      - name: opam cache
        id: opam-cache
        uses: actions/cache@v2.1.2
        with:
          path: ~/.opam
          key: "${{ matrix.os }}-${{ matrix.ocaml-version }}"

      - uses: avsm/setup-ocaml@v1.1.3
        with:
          ocaml-version: "${{ matrix.ocaml-version }}"

      - uses: actions/setup-python@v2.1.4
        with:
          python-version: "3.x"

      - uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable

      - uses: actions/setup-go@v2.1.3
        with:
          go-version: "1.x"

      - name: copy files to config dir
        run: |
          mkdir -p $HOME/.config
          cp -rv $PWD $HOME/.config/nvim

      - name: bootstrap from config dir
        env:
          NVIM_DEBUG: 1
        run: |
          eval "$(opam env)"
          make -j -f $HOME/.config/nvim/Makefile bootstrap
