name: Build
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
jobs:
  bootstrap:
    strategy:
      matrix:
        os:
          - macos-11
          - ubuntu-latest

    name: bootstrap
    runs-on: ${{ matrix.os }}
    steps:
      - name: install neovim (macos)
        if: runner.os == 'macOS'
        run: |
          curl -L https://github.com/neovim/neovim/releases/download/nightly/nvim-macos.tar.gz | sudo tar -C /usr/local --strip 1 -xzf -

      - name: install neovim (linux)
        if: runner.os == 'Linux'
        run: |
          curl -L https://github.com/neovim/neovim/releases/download/nightly/nvim-linux64.tar.gz | sudo tar -C /usr/local --strip 1 -xzf -

      - name: install zsh & linuxbrew on Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install -y zsh
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          echo "PATH=/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:${PATH}" >>${GITHUB_ENV}
        env:
          NONINTERACTIVE: 1

      - name: set brew env vars
        run: |
          echo "HOMEBREW_PREFIX=$(brew --prefix)" >>${GITHUB_ENV}
          echo "HOMEBREW_NO_INSTALL_CLEANUP=1" >>${GITHUB_ENV}
          echo "HOMEBREW_NO_INSTALL_FROM_API=" >>${GITHUB_ENV}

      - name: brew hax (macos hack)
        if: runner.os == 'macOS'
        run: |
          brew unlink python@3.11
          brew link --overwrite python@3.11
          brew untap homebrew/core
          brew untap homebrew/cask

      - name: install early dependencies
        run: |
          brew update
          brew install coreutils jq

      - uses: actions/checkout@v3.5.3

      - uses: actions/setup-python@v4.7.0
        id: setup-python
        with:
          python-version: "3.11"

      - uses: actions/setup-go@v4.0.1
        with:
          go-version: "1.x"
          cache-dependency-path: nvim/langservers/go.sum

      - name: get repo versions
        id: get-repo-versions
        run: |
          git ls-remote https://github.com/golang/tools.git master | awk '{print "golang-tools-version=" $1}' >>${GITHUB_OUTPUT}
          git ls-remote https://git.sr.ht/~technomancy/fnlfmt master | awk '{print "fnlfmt-version=" $1}' >>${GITHUB_OUTPUT}
          git ls-remote https://github.com/fwcd/kotlin-language-server.git main | awk '{print "kotlin-ls-version=" $1}' >>${GITHUB_OUTPUT}
          git ls-remote https://github.com/GroovyLanguageServer/groovy-language-server.git main | awk '{print "groovy-ls-version=" $1}' >>${GITHUB_OUTPUT}

      - name: langservers cache
        id: nvim-langservers-cache
        uses: actions/cache@v3.3.1
        with:
          path: ~/.cache/nvim/langservers
          key: "${{ runner.os }}-${{ hashFiles('nvim/scripts/bootstrap.py') }}-${{ steps.setup-python.outputs.python-version }}-${{ steps.get-repo-versions.outputs.golang-tools-version }}-${{ steps.get-repo-versions.outputs.fnlfmt-version }}-${{ steps.get-repo-versions.outputs.kotlin-ls-version }}-${{ steps.get-repo-versions.outputs.groovy-ls-version }}"
          restore-keys: "${{ runner.os }}-${{ hashFiles('nvim/scripts/bootstrap.py') }}-${{ steps.setup-python.outputs.python-version }}-"

      - name: gradle cache
        id: gradle-cache
        uses: actions/cache@v3.3.1
        with:
          path: ~/.gradle
          key: "${{ runner.os }}-${{ hashFiles('nvim/scripts/bootstrap.py') }}-${{ steps.get-repo-versions.outputs.kotlin-ls-version }}-${{ steps.get-repo-versions.outputs.groovy-ls-version }}"
          restore-keys: "${{ runner.os }}-${{ hashFiles('nvim/scripts/bootstrap.py') }}-"

      - name: get luajit version
        id: get-luajit-version
        run: |
          nvim -l - <<<'print("version=" .. jit.version)' 2>>${GITHUB_OUTPUT}

      - name: get versions from brew
        id: brew-versions
        run: |
          echo "pcre-version=$(brew info pcre --json | jq -r '.[0].versions.stable')" >>${GITHUB_OUTPUT}
          echo "rtx-version=$(brew info rtx --json | jq -r '.[0].versions.stable')" >>${GITHUB_OUTPUT}

      - name: set MACOSX_DEPLOYMENT_TARGET
        id: macosx-deployment-target
        run: |
          echo "MACOSX_DEPLOYMENT_TARGET=$(sw_vers -productVersion)" >>${GITHUB_ENV}
          echo "product-version=$(sw_vers -productVersion)" >>${GITHUB_OUTPUT}

      - name: rtx cache
        id: rtx-cache
        uses: actions/cache@v3.3.1
        with:
          path: ~/.local/share/rtx
          key: "${{ runner.os }}-${{ steps.brew-versions.outputs.rtx-version }}"

      - name: hererocks cache
        id: nvim-hererocks-cache
        uses: actions/cache@v3.3.1
        with:
          path: ~/.cache/nvim/hr
          key: "${{ runner.os }}-${{ steps.brew-versions.outputs.pcre-version }}-${{ steps.get-luajit-version.outputs.version }}-${{ steps.macosx-deployment-target.outputs.product-version }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('nvim/vimfiles-dev-1.rockspec') }}"

      - name: virtualenv cache
        id: nvim-virtualenv-cache
        uses: actions/cache@v3.3.1
        with:
          path: ~/.cache/nvim/venv
          key: "${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('nvim/langservers/requirements.txt') }}"
          restore-keys: "${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-"

      # this will always cache miss, but the idea is to reuse work between
      # pushes by leveraging restore-keys.
      - name: mr cache
        id: mr-cache
        uses: actions/cache@v3.3.1
        with:
          path: ~/.local/share/nvim/site/pack/mr
          key: "${{ runner.os }}-${{ hashFiles('nvim/scripts/mrconfig') }}-${{ github.sha }}"
          restore-keys: "${{ runner.os }}-${{ hashFiles('nvim/scripts/mrconfig') }}-"

      - name: run setup
        run: |
          timeout -k 10s 30m ./bootstrap/setup

      - name: nvim lint & tests
        run: |
          env FSOUZA_DOTFILES_DIR=${PWD} make nvim-tests nvim-lint
        env:
          NVIM_TEST_TIMEOUT: 10000

  pre-commit:
    name: pre-commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3

      - uses: actions/setup-python@v4.7.0
        with:
          python-version: 3.x
          cache: pip

      - name: install pre-commit
        run: pip install pre-commit

      - name: pre-commit cache
        uses: actions/cache@v3.3.1
        with:
          path: ~/.cache/pre-commit
          key: "pc-${{ hashFiles('.pre-commit-config.yaml') }}"
          restore-keys: "pc-"

      - run: pre-commit run --all-files --show-diff-on-failure

  unblock-pr:
    name: unblock-pr
    runs-on: ubuntu-latest
    needs:
      - bootstrap
      - pre-commit
    steps:
      - run: "true"
