on:
  push:
    branches:
      - main

permissions:
  contents: write

name: push to gh-pages
jobs:
  build:
    name: push to gh-pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.4

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
