name: Update langservers
on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-langservers:
    name: Update language servers submodules
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: submodule update
        run: git submodule update --init

      - name: git config
        run: git remote set-url origin https://fsouza:${GITHUB_PASSWORD}@github.com/fsouza/vimfiles.git
        env:
          GITHUB_PASSWORD: ${{ secrets.VIMFILES_GH_TOKEN }}

      - name: fetch hub
        run: |
          curl -sL hub.tgz https://github.com/github/hub/releases/download/v2.13.0/hub-linux-amd64-2.13.0.tgz | \
            sudo tar -C /usr -xzf - --strip-components 1
          hub --version

      - name: bump submodules
        run: |
          git config --local user.name "GitHub Action"
          git config --local user.email "action@github.com"
          git switch -c "update-submodules-$(date +%Y%m%d%H%M%S)" origin/master
          git submodule foreach 'git fetch origin master && git checkout FETCH_HEAD'
          git status --short --no-branch | \
            grep langservers/ | \
            awk '{print $2}' | \
            xargs -I FILE git commit -m "Update FILE" FILE

      - name: open PR
        run: |
          hub pull-request \
            --push \
            --message "Bump language servers" \
            --message 'Updated servers:' \
            --message "$(git diff --name-only origin/master | sed -e 's/^/- /')" \
            --labels automerge
        env:
          GITHUB_TOKEN: ${{ secrets.VIMFILES_GH_TOKEN }}
